'use strict';
const PEOPLE = [
 {id:'liubei',name:'刘备',short:'备',role:'仁心使君 · 诚意引路人',title:'三次登门，一片诚心',quote:'诚意，不止在第一声叩门。',desc:'以仁厚待人，以诚意求贤。在这场三顾之旅中，他邀请你一起学习倾听、耐心与尊重。',file:'assets/liubei.png'},
 {id:'zhugeliang',name:'诸葛亮',short:'亮',role:'卧龙先生 · 智慧讲述者',title:'一柄羽扇，胸中有天下',quote:'看清眼前，也要望见远方。',desc:'羽扇纶巾，心有丘壑。他在草庐中等待一位知己，也会带你认识《隆中对》中思考时势、规划未来的智慧。',file:'assets/zhugeliang.png'},
 {id:'guanyu',name:'关羽',short:'羽',role:'忠义同行 · 沉稳守护者',title:'青龙在侧，忠义在心',quote:'同行之路，贵在守信。',desc:'青衣长髯，沉稳坚定。同行寻贤时，他陪你守住对他人的尊重，也守住对朋友的承诺。',file:'assets/guanyu.png'},
 {id:'zhangfei',name:'张飞',short:'飞',role:'率真伙伴 · 趣味破冰者',title:'爽朗一笑，热意满怀',quote:'别急，好故事值得等一等！',desc:'豪爽率真，热情满怀。他手中的一碗面，为这场古今相遇添上生活气息；故事中，他也和你一起学会耐心。',file:'assets/zhangfei.jpg'}
];
const CHAPTERS=[
 {name:'一顾隆中',number:'壹',tag:'壹 · 初访',kicker:'第一章 · 寻贤',guide:0,desc:'一位求贤的使君，一位未曾谋面的卧龙。和刘备一起叩响草庐的门，开启这场相遇。',stamp:'诚',stampName:'寻贤之诚',place:'隆中 · 草庐前',steps:[
   {speaker:0,text:'听闻卧龙先生在隆中躬耕，我愿亲自登门，请教天下之事。你愿与我们同行吗？',next:'与刘关张同行'},
   {speaker:0,text:'童子说，先生今日外出，归期未定。这一次未能相见，我们该怎样做？',choices:['留下问候，择日再访','责怪童子，请先生马上回来'],correct:0,feedback:'求贤始于尊重。没有见到，也不减这一份诚意。',wrong:'先生不在，童子也无法催他回来。试着用尊重表达诚意。'},
   {speaker:0,text:'今日虽未得相见，我的心意并未改变。请转告先生，刘备还会再来。',next:'留下「寻贤之诚」印记'}]},
 {name:'再访候雪',number:'贰',tag:'贰 · 再访',kicker:'第二章 · 守候',guide:2,desc:'风雪挡不住求贤的脚步。当又一次扑空，跟随关羽与张飞，做出关于耐心的选择。',stamp:'礼',stampName:'候贤之礼',place:'隆中 · 风雪途中',steps:[
   {speaker:2,text:'山路漫长，风雪渐起。兄长仍坚持再访先生。真正的诚意，怎会只来一次？',next:'踏雪赴约'},
   {speaker:3,text:'又没见到先生？等来等去，真让人心急！你说，我们要不要就此回去？',choices:['缓一缓，尊重先生，再寻相见的机会','认定先生故意怠慢，从此不来'],correct:0,feedback:'等待不是白费。能够理解别人的处境，才有相知的可能。',wrong:'一次未遇，不足以判断别人的心意。再多一些理解吧。'},
   {speaker:2,text:'礼，不只在相见时的作揖，也在尚未相见时的体谅。我们且带着这份耐心，再走一程。',next:'留下「候贤之礼」印记'}]},
 {name:'三顾问策',number:'叁',tag:'叁 · 相见',kicker:'第三章 · 相知',guide:1,desc:'草庐的门终于打开。听诸葛亮谈时势、论远谋，在《隆中对》的智慧中完成这场相见。',stamp:'智',stampName:'问策之智',place:'隆中 · 草庐之中',steps:[
   {speaker:0,text:'第三次来到草庐，终于得见先生。我愿虚心倾听，也愿问一问，前路该怎样走。',next:'入草庐，听卧龙'},
   {speaker:1,text:'谋事不能只凭一时热情。《隆中对》启发我们：先看清形势，再寻找自身的立足之地。遇到难题时，你会怎么做？',choices:['分析条件，明确目标，再制定长远计划','只看眼前输赢，想到什么就做什么'],correct:0,feedback:'这份「智」是先思考，再行动。把古人的智慧带回今天的生活。',wrong:'一时的行动，未必通向想去的地方。先看清条件和目标吧。'},
   {speaker:1,text:'三次相访，让诚意有了回响。相逢之后，更有一起向前的路。此刻，愿这份智慧与你同行。',next:'留下「问策之智」印记'}]}
];
let chapter=0, hero=1, storyStep=0, storyAnswered=false, detailPerson=1, sheetReady=false;
let completed=[];
try{const saved=JSON.parse(localStorage.getItem('sangu-stamps')||'[]');completed=Array.isArray(saved)?saved.filter(v=>Number.isInteger(v)&&v>=0&&v<=2):[];}catch{}
const $=id=>document.getElementById(id);
const probe=new Image();probe.onload=()=>{sheetReady=true;renderHero();renderCharacters();};probe.src='assets/ip-sheet.png';
function art(person,element){element.classList.remove('sheet-art');element.style.backgroundPosition='';element.style.backgroundSize='';if(sheetReady){const bounds=[[0,543],[543,1080],[1080,1590],[1590,2172]][person],width=bounds[1]-bounds[0];element.classList.add('sheet-art');element.style.backgroundImage='none';element.setAttribute('role','img');element.setAttribute('aria-label',PEOPLE[person].name+'人物 IP');element.innerHTML=`<svg viewBox="${bounds[0]} 0 ${width} 724" width="100%" height="100%" preserveAspectRatio="xMidYMid meet" aria-hidden="true" style="overflow:hidden"><image href="assets/ip-sheet.png" width="2172" height="724"/></svg>`;}else{element.removeAttribute('role');element.innerHTML=`<img src="${PEOPLE[person].file}" alt="${PEOPLE[person].name}人物 IP">`;}}
function renderHero(){art(hero,$('hero-art'));$('hero-name').textContent=PEOPLE[hero].name;$('hero-title').textContent=PEOPLE[hero].title;$('hero-switch').innerHTML=PEOPLE.map((p,i)=>`<button class="${hero===i?'selected':''}" data-hero="${i}" aria-label="选择${p.name}" aria-pressed="${hero===i}">${p.short}</button>`).join('');}
function chooseChapter(index){chapter=index;const c=CHAPTERS[chapter];$('chapter-kicker').textContent=c.kicker;$('chapter-title').textContent=c.name;$('chapter-desc').textContent=c.desc;$('chapter-guide').textContent='同行人 · '+PEOPLE[c.guide].name;$('scene-tag').textContent=c.tag;document.querySelectorAll('[data-chapter]').forEach(btn=>btn.setAttribute('aria-selected',String(Number(btn.dataset.chapter)===chapter)));}
function switchView(name){if(!['journey','characters','collection'].includes(name))return;document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==name+'-view');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='collection')renderStamps();window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
function renderCharacters(){const grid=$('character-grid');grid.innerHTML=PEOPLE.map((p,i)=>`<button class="character-card" data-person="${i}"><div class="card-art" id="card-art-${i}"></div><h2>${p.name}</h2><span class="role">${p.role}</span><p>${p.quote}</p><span class="text-btn">翻开人物故事</span></button>`).join('');PEOPLE.forEach((_,i)=>art(i,$('card-art-'+i)));}
function showDetail(person){detailPerson=person;const p=PEOPLE[person];art(person,$('detail-art'));$('detail-role').textContent=p.role;$('detail-name').textContent=p.name;$('detail-quote').textContent='“'+p.quote+'”';$('detail-description').textContent=p.desc;$('detail-dialog').showModal();}
function beginStory(index=chapter){chooseChapter(index);storyStep=0;renderStory();$('story-dialog').showModal();}
function renderStory(){const c=CHAPTERS[chapter],s=c.steps[storyStep];storyAnswered=false;art(s.speaker,$('story-art'));$('story-number').textContent=c.number;$('story-place').textContent=c.place;$('story-step').textContent=c.kicker+' · '+(storyStep+1)+'/3';$('story-name').textContent=c.name;$('story-speaker').textContent=PEOPLE[s.speaker].name+' · 原创互动对白';$('story-text').textContent=s.text;$('story-feedback').textContent='';$('story-choices').innerHTML=s.choices?s.choices.map((t,i)=>`<button class="choice-btn" data-choice="${i}">${t}</button>`).join(''):'';$('story-next').hidden=!!s.choices;$('story-next').textContent=s.next||'继续这段故事';}
function answerStory(index){const s=CHAPTERS[chapter].steps[storyStep];if(!s.choices||storyAnswered)return;const correct=index===s.correct;const button=document.querySelector(`[data-choice="${index}"]`);button.classList.add(correct?'correct':'incorrect');$('story-feedback').textContent=correct?s.feedback:s.wrong;if(correct){storyAnswered=true;document.querySelectorAll('[data-choice]').forEach(b=>b.disabled=true);$('story-next').hidden=false;$('story-next').textContent='把这份心意带向前';}}
function nextStory(){if(storyStep<2){storyStep++;renderStory();return;}if(!completed.includes(chapter)){completed.push(chapter);try{localStorage.setItem('sangu-stamps',JSON.stringify(completed));}catch{}}$('story-dialog').close();renderStamps();toast('已收集「'+CHAPTERS[chapter].stampName+'」印记');if(chapter<2)chooseChapter(chapter+1);else switchView('collection');}
function renderStamps(){document.querySelectorAll('.count').forEach(e=>e.textContent=completed.length);$('collection-note').textContent=`已收集 ${completed.length} / 3 枚印记`;$('stamp-grid').innerHTML=CHAPTERS.map((c,i)=>`<div class="stamp-card ${completed.includes(i)?'earned':''}"><div class="stamp-emblem">${c.stamp}</div><h2>${c.stampName}</h2><p>${completed.includes(i)?'已抵达 · '+c.name:'待开启 · '+c.name}</p><button class="text-btn" data-replay="${i}">${completed.includes(i)?'重温这段故事':'去收集这枚印记'}</button></div>`).join('');$('collection-summary').textContent=completed.length===3?'诚以求贤，礼以待人，智以向前。三顾的回响，此刻与你同行。':'从第一声叩门开始，把诚意留在隆中。';}
function showInfo(title,html){$('info-content').innerHTML=`<h2 id="info-title">${title}</h2>${html}`;$('info-dialog').showModal();}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),3500);}
document.addEventListener('click',event=>{const view=event.target.closest('[data-view]');if(view)switchView(view.dataset.view);const h=event.target.closest('[data-hero]');if(h){hero=Number(h.dataset.hero);renderHero();}const c=event.target.closest('[data-chapter]');if(c)chooseChapter(Number(c.dataset.chapter));const p=event.target.closest('[data-person]');if(p)showDetail(Number(p.dataset.person));const choice=event.target.closest('[data-choice]');if(choice)answerStory(Number(choice.dataset.choice));const replay=event.target.closest('[data-replay]');if(replay)beginStory(Number(replay.dataset.replay));if(event.target.closest('[data-close]'))event.target.closest('dialog').close();});
$('story-start').onclick=()=>beginStory();$('story-next').onclick=nextStory;$('hero-detail').onclick=()=>showDetail(hero);$('detail-companion').onclick=()=>{hero=detailPerson;renderHero();$('detail-dialog').close();switchView('journey');toast(PEOPLE[hero].name+'已与你同行');};
$('marker-open').onclick=()=>showInfo('一张卡，一场相见',`<p>先把展示卡打印出来，或在另一块屏幕上打开。进入 AR 后，让镜头完整看见卡片中间的黑白方框。</p><img class="marker-preview" src="assets/hiro.png" alt="Hiro AR 识别图"><a class="outline-btn" href="poster.html" target="_blank" rel="noopener">打开可打印展示卡</a><p class="note">建议打印为 A4，保留识别图周围的白边；在光线充足的位置体验。</p>`);
$('qr-open').onclick=()=>showInfo('把奇遇带到手机',`<p>用手机扫一扫，打开“三顾襄阳”。AR 体验需要允许摄像头访问。</p><img class="large-qr" data-entry-qr alt="三顾襄阳手机入口二维码"><p class="note">微信内若无法启动镜头，可从右上角菜单选择在系统浏览器中打开。</p>`);
$('about-button').onclick=()=>showInfo('三顾襄阳',`<p>以三顾茅庐的故事为线索，将襄阳隆中文化与四位原创人物 IP 连接起来。</p><h3>三次相访，三种心意</h3><p>一顾寻贤之诚，二顾候贤之礼，三顾问策之智。你在故事里作出选择，也把人物带进眼前的空间。</p><h3>AR 相见</h3><p>镜头识别展示卡后，人物会以立体纸偶的形式出现。移动展示卡，人物也会跟随移动。角色原画由创作者提供。</p>`);
$('source-open').onclick=()=>showInfo('故事依据与改编',`<p>作品以襄阳隆中文化叙事为主题，参考三顾茅庐及《隆中对》，以游戏对白和“诚、礼、智”任务进行原创改编。</p><p>风雪再访等情节取自文学叙事。页面中的对白、任务与角色性格表达是设计创作，不作为史料原文；张飞持面碗的形象沿用创作者的 IP 设定。</p><h3>参考资料</h3><p><a href="https://www.fohb.gov.cn/info/2022-09/20220925112300_775.html" target="_blank" rel="noopener">湖北省外事办公室：襄阳古隆中景区</a><br><a href="https://wlt.hubei.gov.cn/bmdt/mtjj/202210/t20221025_4364173.shtml" target="_blank" rel="noopener">湖北省文化和旅游厅：千年古隆中，今朝意更新</a></p>`);
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
renderHero();renderCharacters();renderStamps();
if(document.modelContext?.registerTool){for(const tool of[
 {name:'get_sangu_journey',title:'查看三顾之旅状态',description:'读取当前章节、同行人物和本设备已收集的印记。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({chapter:CHAPTERS[chapter].name,companion:PEOPLE[hero].name,stamps:completed.map(i=>CHAPTERS[i].stampName)})},
 {name:'select_sangu_chapter',title:'选择三顾章节',description:'选择故事章节并展示旅程页面，不完成故事或授予印记。',inputSchema:{type:'object',properties:{chapter:{type:'integer',minimum:1,maximum:3}},required:['chapter'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!Number.isInteger(input.chapter)||input.chapter<1||input.chapter>3)throw Error('请选择 1 到 3 之间的章节。');chooseChapter(input.chapter-1);switchView('journey');return{chapter:CHAPTERS[chapter].name};}}
]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}catch{}}}

