'use strict';
const $=id=>document.getElementById(id);
const people=[{name:'刘备',bounds:[0,543],line:'诚意，不止在第一声叩门。愿你以诚待人，也遇见同路的知己。'},{name:'诸葛亮',bounds:[543,1080],line:'谋事，先看清形势；前行，要心有长远。愿这一柄羽扇，带给你思考的灵感。'},{name:'关羽',bounds:[1080,1590],line:'同行之路，贵在守信。关某愿陪你守住心中的忠义，也守住每一个承诺。'},{name:'张飞',bounds:[1590,2172],line:'哈哈！来襄阳，先吃碗热面，再听段好故事！别急，好事值得等一等。'}];
let role=1,mode='setup',markerVisible=false,scene=null,paper=null,size=1,photoUrl=null,photoBlob=null,loadingTimer=null,subtitleTimer=null,session=0;
function status(text,state=''){const s=$('tracking-status');s.className='tracking-status '+state;s.querySelector('span').textContent=text;}
function toast(text){$('ar-toast').textContent=text;$('ar-toast').classList.add('show');setTimeout(()=>$('ar-toast').classList.remove('show'),3500);}
function setRole(index){role=index;$('role-picker').innerHTML=people.map((p,i)=>`<button data-role="${i}" class="${role===i?'selected':''}" aria-pressed="${role===i}">${p.name}</button>`).join('');const p=people[role],w=p.bounds[1]-p.bounds[0];$('preview-character').style.backgroundSize=`${2172/w*100}% 100%`;$('preview-character').style.backgroundPosition=`${p.bounds[0]/(2172-w)*100}% center`;if(paper?.components['ip-paper'])paper.components['ip-paper'].setPerson(role);$('ar-subtitle').hidden=true;window.speechSynthesis?.cancel();}
const libraryLoads=new Map();
function script(src){if(libraryLoads.has(src))return libraryLoads.get(src);const promise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.dataset.library=src;s.onload=resolve;s.onerror=()=>{s.remove();libraryLoads.delete(src);reject(Error('人物效果加载未完成，请检查网络后重试。'));};document.head.append(s);});libraryLoads.set(src,promise);return promise;}
function registerPaper(){if(AFRAME.components['ip-paper'])return;AFRAME.registerComponent('ip-paper',{
 init:function(){this.person=role;this.t=0;this.greetingUntil=0;const T=AFRAME.THREE;this.cameraRotation=new T.Quaternion();this.parentRotation=new T.Quaternion();this.texture=new T.TextureLoader().load('assets/ip-sheet.png',()=>this.setPerson(this.person));this.texture.colorSpace=T.SRGBColorSpace;this.texture.minFilter=T.LinearFilter;this.texture.magFilter=T.LinearFilter;const material=new T.MeshBasicMaterial({map:this.texture,transparent:true,alphaTest:.04,side:T.DoubleSide,depthWrite:true});this.mesh=new T.Mesh(new T.PlaneGeometry(1,.8),material);this.mesh.position.set(0,.4,0);this.el.setObject3D('mesh',this.mesh);this.setPerson(role);},
 setPerson:function(index){this.person=index;const bounds=people[index].bounds;this.texture.repeat.set((bounds[1]-bounds[0])/2172,1);this.texture.offset.set(bounds[0]/2172,0);this.texture.needsUpdate=true;this.mesh.scale.x=(bounds[1]-bounds[0])/724*.8;},
 tick:function(time){this.lastTime=time;if(!this.mesh)return;const gentle=matchMedia('(prefers-reduced-motion: reduce)').matches?0:Math.sin(time*.0018);this.mesh.position.y=.4+gentle*.02;const camera=this.el.sceneEl.camera;if(camera){camera.getWorldQuaternion(this.cameraRotation);this.el.object3D.getWorldQuaternion(this.parentRotation);this.mesh.quaternion.copy(this.parentRotation.invert()).multiply(this.cameraRotation);}this.mesh.rotateZ(time<this.greetingUntil?Math.sin(time*.018)*.12:gentle*.018);},
 remove:function(){this.mesh?.geometry.dispose();this.mesh?.material.dispose();this.texture?.dispose();this.el.removeObject3D('mesh');}
});}
async function startCamera(){const token=++session;stopMedia();$('preview-scene').hidden=true;$('setup-overlay').hidden=false;$('setup-error').hidden=true;const button=$('camera-start');button.disabled=true;button.textContent='正在准备镜头…';mode='loading';status('正在准备镜头');try{
 if(!window.isSecureContext)throw Error('镜头需要安全连接。请通过已发布的 HTTPS 入口打开作品。');
 if(!navigator.mediaDevices?.getUserMedia)throw Error('当前浏览器没有可用的摄像头接口，请在手机的系统浏览器中打开。');
 if(!document.createElement('canvas').getContext('webgl'))throw Error('当前设备不支持人物渲染。你仍可以查看人物效果预览。');
 const permissionStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});permissionStream.getTracks().forEach(t=>t.stop());if(token!==session)return;
 await script('vendor/aframe.min.js');await script('vendor/aframe-ar.js');if(token!==session)return;registerPaper();
 scene=document.createElement('a-scene');scene.setAttribute('embedded','');scene.setAttribute('vr-mode-ui','enabled: false');scene.setAttribute('renderer','alpha: true; antialias: true; precision: medium; logarithmicDepthBuffer: true;');scene.setAttribute('arjs','sourceType: webcam; debugUIEnabled: false; cameraParametersUrl: assets/camera_para.dat; detectionMode: mono; patternRatio: 0.5;');scene.setAttribute('screenshot','width: 1080; height: 1920;');scene.setAttribute('loading-screen','enabled: false');
 scene.innerHTML='<a-marker type="pattern" url="assets/patt.hiro" smooth="true" smoothCount="5" smoothTolerance="0.01" smoothThreshold="2"><a-entity id="paper-character" ip-paper></a-entity><a-ring color="#b49a66" radius-inner="0.48" radius-outer="0.50" rotation="-90 0 0" position="0 0.025 0" material="opacity: .85; side: double"></a-ring><a-circle color="#173e35" radius=".48" rotation="-90 0 0" position="0 0.012 0" material="opacity: .35; transparent: true; side: double"></a-circle></a-marker><a-entity camera></a-entity>';
 const marker=scene.querySelector('a-marker');marker.addEventListener('markerFound',()=>{if(token!==session)return;markerVisible=true;status('已遇见 · '+people[role].name,'found');$('scan-guide').hidden=true;$('capture-button').disabled=false;$('capture-hint').textContent='移动展示卡，人物会跟随你';});marker.addEventListener('markerLost',()=>{if(token!==session)return;markerVisible=false;status('请把展示卡放回镜头中');$('scan-guide').hidden=false;$('capture-button').disabled=true;$('capture-hint').textContent='识别展示卡后，即可合影';});
 const cameraInit=()=>{if(token!==session)return;const v=document.querySelector('#arjs-video');if(!v||v.readyState<2)return;clearInterval(loadingTimer);mode='ar';$('setup-overlay').hidden=true;$('ar-controls').hidden=false;$('scan-guide').hidden=!markerVisible;status(markerVisible?'已遇见 · '+people[role].name:'请对准展示卡中的黑白方框',markerVisible?'found':'');paper=scene.querySelector('#paper-character');paper.object3D.scale.setScalar(size);alignLayers();};
 $('ar-root').append(scene);scene.addEventListener('loaded',()=>{paper=scene.querySelector('#paper-character');paper.object3D.scale.setScalar(size);});
 let ticks=0;loadingTimer=setInterval(()=>{if(token!==session){clearInterval(loadingTimer);return;}cameraInit();if(++ticks>160&&mode==='loading'){cameraFailure('镜头还没有启动。请允许摄像头访问，或关闭占用镜头的应用后重试。');}},150);
 }catch(error){if(token===session)cameraFailure(error.name==='NotAllowedError'?'摄像头权限未开启。请在浏览器设置中允许访问，再返回作品重试。':error.name==='NotFoundError'?'没有找到可用的镜头。请使用带摄像头的手机，或先查看人物效果。':error.message||'镜头暂时无法启动，请重试或查看人物预览。');}}
function cameraFailure(message){session++;stopMedia();mode='setup';$('setup-overlay').hidden=false;$('ar-controls').hidden=true;$('setup-error').hidden=false;$('setup-error').textContent=message;$('camera-start').disabled=false;$('camera-start').textContent='重新开启摄像头';status('镜头暂未开启');}
function stopMedia(){clearInterval(loadingTimer);window.speechSynthesis?.cancel();const v=document.querySelector('#arjs-video');const source=scene?.systems?.arjs?._arSession?.arSource;const stopVideo=video=>{video?.srcObject?.getTracks?.().forEach(t=>t.stop());video?.remove();};const sourceVideo=source?.domElement;[...new Set([v,sourceVideo])].filter(Boolean).forEach(video=>{stopVideo(video);video.addEventListener('loadedmetadata',()=>stopVideo(video),{once:true});});if(scene){scene.pause();scene.remove();scene=null;paper=null;}markerVisible=false;document.querySelectorAll('.a-enter-vr,.a-enter-ar,.a-orientation-modal,.a-loader-title').forEach(n=>n.remove());$('capture-button').disabled=true;}
function startPreview(){session++;stopMedia();mode='preview';$('setup-overlay').hidden=true;$('preview-scene').hidden=false;$('ar-controls').hidden=false;$('scan-guide').hidden=true;$('capture-button').disabled=true;$('capture-hint').textContent='当前是人物预览，开启镜头后可进行 AR 合影';status('人物预览 · 尚未开启 AR 识别','preview');setRole(role);}
function greet(){if(mode==='ar'&&!markerVisible){toast('先让展示卡进入镜头，故人才能向你问好。');return;}if(mode==='preview'){const p=$('preview-character');p.classList.remove('greeting');void p.offsetWidth;p.classList.add('greeting');setTimeout(()=>p.classList.remove('greeting'),1500);}else if(paper?.components['ip-paper']){const component=paper.components['ip-paper'];component.greetingUntil=(component.lastTime||0)+1600;}subtitle(people[role].name+'向你问好：很高兴与你相见！');}
function subtitle(text){clearTimeout(subtitleTimer);$('ar-subtitle').textContent=text;$('ar-subtitle').hidden=false;subtitleTimer=setTimeout(()=>$('ar-subtitle').hidden=true,12000);}
function narrate(){if(mode==='ar'&&!markerVisible){toast('对准展示卡，再听故人讲述。');return;}subtitle(people[role].line);if('speechSynthesis' in window){window.speechSynthesis.cancel();const speech=new SpeechSynthesisUtterance(people[role].line);speech.lang='zh-CN';speech.rate=.85;window.speechSynthesis.speak(speech);}else toast('当前设备无法播报语音，可以阅读屏幕中的人物对白。');}
async function capture(){if(mode!=='ar'||!markerVisible){toast('识别展示卡后，就可以合影。');return;}try{const video=document.querySelector('#arjs-video');if(!video||video.readyState<2)throw Error('镜头还没有准备好，请稍后再试。');const scale=Math.min(devicePixelRatio||1,2),width=innerWidth,height=innerHeight;const output=document.createElement('canvas');output.width=Math.round(width*scale);output.height=Math.round(height*scale);const ctx=output.getContext('2d');ctx.scale(scale,scale);const vr=video.getBoundingClientRect();ctx.drawImage(video,vr.left,vr.top,vr.width,vr.height);const rr=scene.canvas.getBoundingClientRect();scene.setAttribute('screenshot',{width:Math.round(rr.width*scale),height:Math.round(rr.height*scale)});const render=scene.components.screenshot.getCanvas('perspective');ctx.drawImage(render,rr.left,rr.top,rr.width,rr.height);ctx.fillStyle='rgba(18,46,36,.76)';ctx.fillRect(0,height-54,width,54);ctx.fillStyle='#fff8e4';ctx.font='17px serif';ctx.fillText('三顾襄阳 · 与'+people[role].name+'相见',18,height-22);photoBlob=await new Promise(resolve=>output.toBlob(resolve,'image/png'));if(!photoBlob)throw Error('合影未生成，请再试一次。');if(photoUrl)URL.revokeObjectURL(photoUrl);photoUrl=URL.createObjectURL(photoBlob);$('photo-preview').src=photoUrl;$('photo-download').href=photoUrl;const file=new File([photoBlob],'三顾襄阳-AR合影.png',{type:'image/png'});$('share-photo').hidden=!navigator.canShare?.({files:[file]});$('photo-dialog').showModal();}catch(e){toast(e.message||'合影暂未生成，请再试一次。');}}
function alignLayers(){const video=document.querySelector('#arjs-video');if(!scene?.renderer||!video||video.readyState<2)return;const r=video.getBoundingClientRect();if(r.width<=0||r.height<=0)return;scene.renderer.setSize(r.width,r.height,false);Object.assign(scene.canvas.style,{position:'fixed',left:r.left+'px',top:r.top+'px',width:r.width+'px',height:r.height+'px',margin:'0'});}
window.addEventListener('resize',()=>setTimeout(alignLayers,120));window.addEventListener('arjs-video-loaded',()=>setTimeout(alignLayers,120));
window.addEventListener('camera-error',()=>{if(mode==='loading')cameraFailure('镜头没有成功开启。请允许摄像头访问，并关闭占用镜头的应用后重试。');});
document.addEventListener('click',e=>{const p=e.target.closest('[data-role]');if(p){setRole(Number(p.dataset.role));if(mode==='ar'&&markerVisible)status('已遇见 · '+people[role].name,'found');}if(e.target.closest('[data-close]'))e.target.closest('dialog').close();});
$('size-control').oninput=e=>{size=Number(e.target.value);$('size-output').textContent=size.toFixed(1)+'×';if(paper)paper.object3D.scale.setScalar(size);$('preview-character').style.scale=size;};$('camera-start').onclick=startCamera;$('preview-start').onclick=startPreview;$('greet-button').onclick=greet;$('listen-button').onclick=narrate;$('capture-button').onclick=capture;$('help-button').onclick=()=>$('help-dialog').showModal();$('restart-button').onclick=()=>{$('help-dialog').close();startCamera();};$('share-photo').onclick=async()=>{try{await navigator.share({files:[new File([photoBlob],'三顾襄阳-AR合影.png',{type:'image/png'})],title:'三顾襄阳 · AR 相见'});}catch(e){if(e.name!=='AbortError')toast('可以通过“保存这张合影”保留图片。');}};
window.addEventListener('pagehide',()=>{session++;stopMedia();if(photoUrl)URL.revokeObjectURL(photoUrl);});setRole(role);

